# Generated by Django 5.0.1 on 2024-01-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
