# Generated by Django 5.0.1 on 2024-01-26 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_tag_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product_tag',
            name='product_sku_tag_id_unique',
        ),
        migrations.AlterField(
            model_name='product_tag',
            name='product_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='product_tag',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='product_tag',
            unique_together={('product_sku', 'tag_id')},
        ),
    ]
