# Generated by Django 5.0.1 on 2024-01-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_product_tag_product_sku_tag_id_unique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
