# Generated by Django 5.0.1 on 2024-01-27 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_tag_tag_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product_Tag",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
