# Generated by Django 5.0.1 on 2024-01-26 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=15)),
                ('date_received', models.DateTimeField()),
                ('product_sku', models.CharField(max_length=10)),
                ('quantity', models.BigIntegerField()),
                ('location', models.CharField(max_length=150)),
                ('remarks', models.CharField(max_length=250)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inbounds.supplier')),
            ],
        ),
    ]
