# Generated by Django 5.0.1 on 2024-01-26 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=15)),
                ('date_received', models.DateTimeField()),
                ('product_sku', models.CharField(max_length=10)),
                ('quantity', models.BigIntegerField()),
                ('destination', models.CharField(max_length=150)),
                ('remarks', models.CharField(max_length=250)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outbounds.customer')),
            ],
        ),
    ]
